#!/usr/bin/env sh
# Independent verification. Needs only a checkout of this repository.
# Steps 1-3 need no network and no credentials.
# Step 4 needs cosign and reaches rekor.sigstore.dev.
#
#   ./verify.sh          steps 1-3
#   ./verify.sh --tlog   steps 1-4

set -eu
cd "$(dirname "$0")"

IDENTITY="https://github.com/riskloom/ledger-genesis/.github/workflows/anchor-sha256sums.yml@refs/heads/main"
ISSUER="https://token.actions.githubusercontent.com"

if command -v sha256sum >/dev/null 2>&1; then
  _d() { sha256sum "$1" | cut -d' ' -f1; }
elif command -v shasum >/dev/null 2>&1; then
  _d() { shasum -a 256 "$1" | cut -d' ' -f1; }
else
  echo "need sha256sum or shasum" >&2; exit 1
fi

fail=0
say() { printf '%s\n' "$*"; }

say "== 1. every file's digest matches the line recorded for it in SHA256SUMS"
n=0; bad=0
# SHA256SUMS has NO trailing LF by construction, so a plain `read` loop would
# silently drop its last line. The `|| [ -n "$line" ]` clause is what stops this
# check from quietly skipping a file.
while IFS= read -r line || [ -n "$line" ]; do
  [ -n "$line" ] || continue
  f=${line% *}; want=${line##* }
  n=$((n+1))
  if [ ! -f "$f" ]; then say "   MISSING  $f"; bad=$((bad+1)); continue; fi
  got=$(_d "$f")
  [ "$got" = "$want" ] || { say "   MISMATCH $f"; say "            recorded $want"; say "            actual   $got"; bad=$((bad+1)); }
done < SHA256SUMS
say "   $n files listed, $bad bad"
expected=$(( $(wc -l < SHA256SUMS | tr -d " ") + 1 ))
if [ "$n" -ne "$expected" ]; then
  say "   FAIL  read $n lines but SHA256SUMS contains $expected"; fail=1
fi
[ "$bad" -eq 0 ] || fail=1

say ""
say "== 2. SHA256SUMS lists exactly the files present, no more and no fewer"
present=$(find . -type f ! -path './.git/*' ! -name 'SHA256SUMS' \
       ! -name 'cosign.bundle' ! -name 'cosign.sig' \
       ! -name 'cosign.pem' ! -name 'cosign.crt' | sed 's|^\./||' | LC_ALL=C sort)
listed=$(cut -d' ' -f1 SHA256SUMS | LC_ALL=C sort)
if [ "$present" = "$listed" ]; then
  say "   OK  no unlisted file, no listed file absent"
else
  say "   DIFFERENCE (< present but unlisted, > listed but absent):"
  printf '%s\n' "$present" > /tmp/.rl_p.$$; printf '%s\n' "$listed" > /tmp/.rl_l.$$
  diff /tmp/.rl_p.$$ /tmp/.rl_l.$$ | sed 's/^/   /' || true
  rm -f /tmp/.rl_p.$$ /tmp/.rl_l.$$
  fail=1
fi

say ""
say "== 3. SHA256SUMS is byte-exact under the Class B construction, and the root"
if [ -x ./sha256sums.sh ]; then
  if ./sha256sums.sh | cmp -s - SHA256SUMS; then
    say "   OK  regenerating the canonical bytes reproduces SHA256SUMS exactly"
  else
    say "   FAIL  regenerated bytes differ from SHA256SUMS"; fail=1
  fi
fi
ROOT=$(_d SHA256SUMS)
say "   package root = $ROOT"

if [ "${1:-}" = "--tlog" ]; then
  say ""
  say "== 4. the root is committed to the public Sigstore transparency log"
  if ! command -v cosign >/dev/null 2>&1; then
    say "   cosign not installed - skipping"; 
  elif [ ! -f cosign.bundle ]; then
    say "   cosign.bundle not present in this checkout."
    say "   Download it from the release:  gh release download --repo riskloom/ledger-genesis --pattern cosign.bundle"
    fail=1
  else
    cosign verify-blob \
      --bundle cosign.bundle \
      --certificate-identity "$IDENTITY" \
      --certificate-oidc-issuer "$ISSUER" \
      SHA256SUMS && say "   OK  signature and transparency-log entry verified against the pinned identity"
  fi
fi

say ""
if [ "$fail" -eq 0 ]; then say "RESULT: PASS"; else say "RESULT: FAIL"; exit 1; fi
